name: sound_receiver
description: Receives sounds via BLE and plays them.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ble_peripheral: ^2.4.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.0
  permission_handler: ^11.0.0

flutter:
  uses-material-design: true
